name: f22_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: ^1.1.0
  dio: ^4.0.4
  flutter_loggy_dio: ^2.0.0+3
  loggy: ^2.0.1+1
  flutter_loggy: ^2.0.1
  flutter: 
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.2
  dismissible_page: ^0.7.3
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


